name: Build and deploy daily at 01:00 UTC

on:
  schedule:
      - cron: '0 1 * * *'

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.TOKEN }}
